# Generated by Django 3.0.8 on 2020-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='afripaas_title',
        ),
        migrations.AddField(
            model_name='properties',
            name='p_value',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='property',
            field=models.CharField(default='1', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
