# Generated by Django 3.1 on 2020-11-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
