# Generated by Django 3.1 on 2020-11-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0004_auto_20201113_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aftimestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time  stamp'),
        ),
    ]
